//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Fairtech_DataEntities : DbContext
    {
        public Fairtech_DataEntities()
            : base("name=Fairtech_DataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Personnel> Personnels { get; set; }
        public virtual DbSet<Zone> Zones { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<SupplierA> SupplierAs { get; set; }
        public virtual DbSet<Tbank> Tbanks { get; set; }
        public virtual DbSet<Tin> Tins { get; set; }
        public virtual DbSet<Ttout> Ttouts { get; set; }
        public virtual DbSet<TarckingList> TarckingLists { get; set; }
        public virtual DbSet<Tracking> Trackings { get; set; }
    }
}
