//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personnel
    {
        public string Pid { get; set; }
        public string Pname { get; set; }
        public string Puser { get; set; }
        public string Ppass { get; set; }
    }
}
