//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public string Sid { get; set; }
        public string Sname { get; set; }
        public string Staxid { get; set; }
        public string Sbranch { get; set; }
        public string Sphone { get; set; }
        public string Semail { get; set; }
        public string Saddress { get; set; }
    }
}
