//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierA
    {
        public string Aid { get; set; }
        public string Aname { get; set; }
        public string Aphone { get; set; }
        public string Aemail { get; set; }
        public string Adetail { get; set; }
        public string ID { get; set; }
        public string Name { get; set; }
        public string Aline { get; set; }
    }
}
