//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tracking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tracking()
        {
            this.TarckingLists = new HashSet<TarckingList>();
        }
    
        public string Tid { get; set; }
        public string Tdate { get; set; }
        public string Tstatus { get; set; }
        public string Tper { get; set; }
        public string Tsid { get; set; }
        public string Tsname { get; set; }
        public string Tstaxid { get; set; }
        public string Tsbranth { get; set; }
        public string Tsphone { get; set; }
        public string Tsemail { get; set; }
        public string Tsaddress { get; set; }
        public string Tsa { get; set; }
        public string Tzid { get; set; }
        public string Tzname { get; set; }
        public string Tbank { get; set; }
        public string Tbankdate { get; set; }
        public string Ttotail { get; set; }
        public string Tvat { get; set; }
        public string Tvattatoil { get; set; }
        public string Ttatoill { get; set; }
        public string Tla { get; set; }
        public string Tlb { get; set; }
        public string Tlc { get; set; }
        public string Tdetail { get; set; }
        public string Tin { get; set; }
        public string Tout { get; set; }
        public string TResult { get; set; }
        public string Tf { get; set; }
        public string Tff { get; set; }
        public string Tdetaillist { get; set; }
        public string R1 { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TarckingList> TarckingLists { get; set; }
    }
}
